apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-server
  namespace: cluster-config
spec:
  targetNamespace: prefect
  releaseName: prefect-server
  chart:
    spec:
      chart: prefect-server
      sourceRef:
        kind: HelmRepository
        name: prefect
        namespace: cluster-config
  interval: 5m0s
  install:
    remediation:
      retries: 3